name: Sync fork from upstream

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set upstream
        run: |
         git remote add upstream https://github.com/kyrexi/trafyx.git
         git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
